### ISSUE TITLE
problem copying C:\User\AppData\Local\R\win-library\4.3\00LOCK\vctrs\libs\x64\vctrs.dll Permission denied

### ISSUE THREAD

**Issue by NAguirre-Lupano** [jsilve24/philr#27]
Hi, 
Recently I tried to install "philr" since github directly,

> devtools::install_github("jsilve24/philr", force = TRUE)

but I couldn't installed it because I reported this error at the end: 

<details><summary>Details</summary>
<p>

Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\myUser\AppData\Local\R\win-library\4.3\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Users\myUser\AppData\Local\R\win-library\4.3\vctrs\libs\x64\vctrs.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\myUser\AppData\Local\R\win-library\4.3\00LOCK\igraph\libs\x64\igraph.dll to C:\Users\myUser\AppData\Local\R\win-library\4.3\igraph\libs\x64\igraph.dll: Permission denied

</p>
</details> 

I tried to restarting my R session but I still reporting the same error, 
could you help me fixed it please? 
I appreciated

**Comment by jsilve24** [comment]
Looks like you don't have permission to install where it's try to install. My guess is that it has nothing to do with philr.

Sent From My Mobile Device
________________________________
From: NAguirre-Lupano ***@***.***>
Sent: Sunday, June 18, 2023 6:03:51 PM
To: jsilve24/philr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jsilve24/philr] problem copying C:\User\AppData\Local\R\win-library\4.3\00LOCK\vctrs\libs\x64\vctrs.dll Permission denied (Issue #27)


Hi,
Recently I tried to install "philr" since github directly,

devtools::install_github("jsilve24/philr", force = TRUE)

but I couldn't installed it because I reported this error at the end:

Details

Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
problem copying C:\Users\myUser\AppData\Local\R\win-library\4.3\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Users\myUser\AppData\Local\R\win-library\4.3\vctrs\libs\x64\vctrs.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
problem copying C:\Users\myUser\AppData\Local\R\win-library\4.3\00LOCK\igraph\libs\x64\igraph.dll to C:\Users\myUser\AppData\Local\R\win-library\4.3\igraph\libs\x64\igraph.dll: Permission denied

I tried to restarting my R session but I still reporting the same error,
could you help me fixed it please?
I appreciated

**Comment by NAguirre-Lupano** [comment]
I don't know what is going on, this is definitely my computer and my main user, so I should have the permissions to overwrite paths. 
:/

**Comment by jsilve24** [comment]
Can't help you there. Sorry.

Sent From My Mobile Device
________________________________
